
services:
  postgres:
    image: postgres:17.4
    container_name: pg_tmdb
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tmdb_user
      POSTGRES_PASSWORD: tmdb_pass
      POSTGRES_DB: tmdb_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.4
    container_name: redis_db
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pgdata:
